### ISSUE TITLE
Change server token name

### ISSUE THREAD

**Issue by PurpleGuitar** [Bible-Translation-Tools/BTT-Writer-Android#12]
Please update the name of the server token as per Desktop:

https://github.com/Bible-Translation-Tools/BTT-Writer-Desktop/issues/17

**Comment by ChrisJarka** [comment]
Thank you for fixing the name on the token.
I notice that new token contains quite a bit of local computer information. Should that be displayed?
![Snag_74bca4](https://user-images.githubusercontent.com/9850185/121741705-e344ad00-cacc-11eb-9737-4ca928fedbdc.png)

**Comment by AnonymousWalker** [comment]
@ChrisJarka my short answer is yes. We assign the token for each individual machine/device that login to BTT Writer. For the purpose of unique identifier, we want to avoid duplicate token name which may cause an error when they login.
Also, in case there is an issue with one of the tokens, for some reason, the user could go and find the correct token and delete it manually. Having such info is helpful for such situation, though they are not likely to visit this setting.
