### ISSUE TITLE
when submitting an issue I am sent to a UFW site to check on latest release

### ISSUE THREAD

**Issue by ChrisJarka** [Bible-Translation-Tools/BTT-Writer-Android#27]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-android/releases/latest) of the app.
- [ ] Check that a similar issue has not already been opened.

https://github.com/unfoldingWord-dev/ts-android/releases/latest

**Comment by PurpleGuitar** [comment]
This should have been resolved with the feedback token updater change.  Please let us know if you see this problem again.
