### ISSUE TITLE
Latest Release doesn't run on Recent Android Devices

### ISSUE THREAD

**Issue by mondele** [Bible-Translation-Tools/BTT-Writer-Android#35]
On newer devices running late Android 9 and Android 10 (and certain devices: specifically Samsung for sure) builds after commit ef605bc (i.e. starting with 7ca0a70, update the Android SDK) don't run, but immediately crash. This is the behavior for a clean install, but an upgrade starts the app but then hangs on the load screen.

I feel this is somewhat critical, as it impairs new users of newer hardware.

**Comment by mondele** [comment]
I'm sorry. Commit ef605bc also fails to run. It's the previous build,  v1.1.0-20210609, that doesn't immediately crash.

**Comment by PurpleGuitar** [comment]
Thanks @mondele .  I've been working on this issue for the past week or two -- it's pretty tricky.  I'll let you know when I have a build ready for testing.

**Comment by PurpleGuitar** [comment]
Fixed in v1.1.3.
