### ISSUE TITLE
Source added but not showing up

### ISSUE THREAD

**Issue by OpThomasPrime1** [Bible-Translation-Tools/BTT-Writer-Android#76]
<img width="658" alt="Screenshot_20230215_084354" src="https://user-images.githubusercontent.com/106596927/219047937-54d9e4be-3e7f-43e3-86bb-9d77ee1af03c.png">

<img width="392" alt="Screenshot_20230215_084433" src="https://user-images.githubusercontent.com/106596927/219048011-b5ba8074-e670-436e-9f94-e21be55ddc80.png">

I added a source to my project, and when I pushed confirm, the project acted like I had never added a source. When I checked my sources, the source was checked off. To confirm the issue, I tested the same, making new projects in different languages and adding a single source. The issue persisted.

**Comment by PurpleGuitar** [comment]
I'm not able to reproduce this error.  I'm using a Pixel phone emulated by Android Studio.  Could you review these steps and let me know if I'm doing something different than you?

Here are the steps I'm taking:

1. Start with a clean install of BTT-Writer 1.2.0+14.
2. Click "Start a New Translation"
3. Choose "Afaraf"
4. Choose "bible-nt"
5. Choose "Matthew"
6. Observe that we have a new project with no source translation selected.
7. Click the "add source" button in the upper left.

![image](https://user-images.githubusercontent.com/1095575/219749627-d450f5a9-71ed-4c95-9e4c-de6a4575fc40.png)

8. Select English ULB.
9. Click "Confirm."

![image](https://user-images.githubusercontent.com/1095575/219750339-ed5e2588-5e75-4f7b-832a-4735da2ff1ee.png)

10. Observe that the English ULB source is appearing.

![image](https://user-images.githubusercontent.com/1095575/219751124-a99b0539-3784-46a9-a0dd-098e03fadb06.png)

**Comment by OpThomasPrime1** [comment]
So I was able to reproduce it on Android Studios on my Mac. Started a translation of Luke in Afaraf, added Amharic ULB, and then the text showed up as blank. Same thing happened when I added in Bengali ULB. However, when I removed Amharic, the Bengali text showed up. After this point, adding the Amharic ULB started working again, and I was even able to start a new project with Amharic ULB only and the text showed up. It is elusive, but perhaps the problem lies with this particular source?

**Comment by OpThomasPrime1** [comment]
<img width="1440" alt="Screenshot 2023-02-21 at 10 57 13 AM" src="https://user-images.githubusercontent.com/106596927/220395730-97bb4ee2-1cbc-4e8f-857e-4304564107eb.png">

<img width="1440" alt="Screenshot 2023-02-21 at 10 58 57 AM" src="https://user-images.githubusercontent.com/106596927/220395923-cff5a7a2-12fe-4bd3-be6e-c8d8e0dda1ae.png">

It seems to happen with new projects, on a fresh install, with Amharic selected as the source text, here I was able to reproduce it again with John

**Comment by OpThomasPrime1** [comment]
Here I used an emulated Pixel tablet, made a project of Romans, and this time added only the English ULB

<img width="1440" alt="Screenshot 2023-02-21 at 11 05 45 AM" src="https://user-images.githubusercontent.com/106596927/220397995-2f5c0955-b3fa-418a-a64b-c12df924f6b7.png">
